### ISSUE TITLE
seemingly broken commands

### ISSUE THREAD

**Issue by JohnUrban** [LeeMendelowitz/maligner#9]
Hi,

I am just reporting this in case I am bringing it to your attention. There is no urgent need to resolve this - just thought you should know.

The following commands raise errors:

```
alignments_maligner_to_malign_viz -h
Traceback (most recent call last):
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/alignments_maligner_to_malign_viz", line 10, in <module>
    from malignpy.malign_viz.alignments import MalignVizAlignment
ImportError: No module named malign_viz.alignments

alignments_maligner_to_soma rmaps_to_asm.pfx.aln asm.BamHI.maps rmap.BamHI.maps 
2016-05-03 13:08:07,616 - alignments_maligner_to_soma - INFO - Alignment file: rmaps_to_asm.pfx.aln
2016-05-03 13:08:07,616 - alignments_maligner_to_soma - INFO - Query map file: rmap.BamHI.maps
2016-05-03 13:08:07,616 - alignments_maligner_to_soma - INFO - Ref maps file: asm.BamHI.maps
2016-05-03 13:08:07,617 - alignments_maligner_to_soma - INFO - Output file: STDOUT
2016-05-03 13:08:07,617 - alignments_maligner_to_soma - INFO - reading query maps
2016-05-03 13:08:07,618 - alignments_maligner_to_soma - INFO - reading ref maps
2016-05-03 13:08:07,619 - alignments_maligner_to_soma - INFO - done. Converting alignments... (patience)
Traceback (most recent call last):
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/alignments_maligner_to_soma", line 115, in <module>
    maligner_to_soma(input_file, output_file, query_map_dict, ref_map_dict)
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/examples/ovl/malignpy/common/wrap_file_function.py", line 55, in wrapped
    return func(*args, **kwargs)
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/alignments_maligner_to_soma", line 92, in maligner_to_soma
    tree.write(output_file, pretty_print = True, xml_declaration=True, encoding="iso-8859-1")
TypeError: write() got an unexpected keyword argument 'pretty_print'


filter_alignments -h
Traceback (most recent call last):
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/filter_alignments", line 15, in <module>
    import malignpy.core.null_distribution
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/lib/malignpy/core/null_distribution.py", line 20, in <module>
    from malignpy.maps.SOMAMap import SOMAMap
ImportError: No module named SOMAMap


generate_random_maps rmap.BamHI.maps 1 20
Traceback (most recent call last):
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/generate_random_maps", line 47, in <module>
    run(args.maps_file, args.output, args.num_maps, args.num_frags)
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/lib/malignpy/common/wrap_file_function.py", line 55, in wrapped
    return func(*args, **kwargs)
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/generate_random_maps", line 22, in run
    for i in range(NUM_MAPS):
NameError: global name 'NUM_MAPS' is not defined


soma_consensus_maps 
Traceback (most recent call last):
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/soma_consensus_maps", line 19, in <module>
    type = 'str', help='Alignments file. Use "-" for STDIN')
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1286, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'str' is not callable

soma_query_maps
Traceback (most recent call last):
  File "/Users/johnurban/searchPaths/software/genomemapping/maligner/maligner/build/bin/soma_query_maps", line 18, in <module>
    type = 'str', help='Alignments file. Use "-" for STDIN')
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1286, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'str' is not callable
```

**Comment by JohnUrban** [comment]
Looks like I can 'fix' the "filter_alignments" problem by downloading your soma_v3

```
git clone https://github.com/LeeMendelowitz/SOMA-V3.git
```

and symlinking SOMAMap.py into maligner/build/lib/malignpy/maps

```
cd maligner/build/lib/malignpy/maps
ln -s /path/to/SOMA-V3/bin/SOMAMap.py .
```
